# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rwMetropolis using Rcpp
#' @description rwMetropolis using Rcpp
#' @param n the number of samples
#' @param sigma sigma of normal distribution
#' @param x0 initial value
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rwMetropolis(1,50,10)
#' }
#' @export
rwMetropolis <- function(sigma, x0, n) {
    .Call('_StatComp20093_rwMetropolis', PACKAGE = 'StatComp20093', sigma, x0, n)
}

